#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
Args="${@:2}"

check_nodejs_version() {
	echo 'Obtaining Node.js version from .node-version'
	source $NVM_DIR/nvm.sh

	nvm use $(cat $SCRIPT_DIR/.node-version) || {
		echo 'Failed to obtain Node.js version from .node-version. Exitting.'
		echo 'Would you like to install it now? (y/n)'
		read -r answer
		[[ $answer == "y" ]] && nvm install $(cat $SCRIPT_DIR/.node-version)
		exit 1
	}
	
	ls $SCRIPT_DIR/node_modules/.bin/ >/dev/null 2>&1 || {
		echo 'Node.js dependencies not installed. Installing now...'
		pnpm install
	}
}

case $1 in
	'database'|'db')
		check_nodejs_version
		pnpm run exec $SCRIPT_DIR/app/database/cmdline.ts $Args
	;;
	'sqlite'|'sql')
		sqlite3 $SCRIPT_DIR/app/database/database.sqlite3 $Args
	;;
	'start'|'s')
		check_nodejs_version
		pnpm run dev $Args
	;;
	'test'|'t')
		check_nodejs_version
		pnpm t $Args
	;;
	'exec'|'x')
		check_nodejs_version
		pnpm run exec $Args
	;;
	*)
		echo Unhandled argument $1. Exitting.
		exit 1
	;;
esac

exit $?
